# SPDX-License-Identifier: BUSL-1.1
#
# Copyright (C) 2023, Berachain Foundation. All rights reserved.
# Use of this software is govered by the Business Source License included
# in the LICENSE file of this repository and at www.mariadb.com/bsl11.
#
# ANY USE OF THE LICENSED WORK IN VIOLATION OF THIS LICENSE WILL AUTOMATICALLY
# TERMINATE YOUR RIGHTS UNDER THIS LICENSE FOR THE CURRENT AND ALL OTHER
# VERSIONS OF THE LICENSED WORK.
#
# THIS LICENSE DOES NOT GRANT YOU ANY RIGHT IN ANY TRADEMARK OR LOGO OF
# LICENSOR OR ITS AFFILIATES (PROVIDED THAT YOU MAY USE A TRADEMARK OR LOGO OF
# LICENSOR AS EXPRESSLY REQUIRED BY THIS LICENSE).
#
# TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE LICENSED WORK IS PROVIDED ON
# AN “AS IS” BASIS. LICENSOR HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS,
# EXPRESS OR IMPLIED, INCLUDING (WITHOUT LIMITATION) WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND
# TITLE.

version: '3.3'

services:
  node0:
    container_name: polard-node0
    image: "polard/seed:v0.0.0"
    ports:
      - "26656-26658:26656-26658"
      - "9090-9091:9090-9091"
      - "8545-8546:8545-8546"
    environment:
      - ID=0
    volumes:
      - type: bind
        source: ./temp/seed0
        target: /root
    networks:
      localnet:
        ipv4_address: 192.168.10.10

  node1:
    container_name: polard-node1
    image: "polard/seed:v0.0.0"
    ports:
      - "26659-26661:26656-26658"
      - "9092-9093:9090-9091"
      - "8547-8548:8545-8546"
    environment:
      - ID=1
    volumes:
      - type: bind
        source: ./temp/seed1
        target: /root
    networks:
      localnet:
        ipv4_address: 192.168.10.11

  node2:
    container_name: polard-node2
    image: "polard/seed:v0.0.0"
    ports:
      - "26662-26664:26656-26658"
      - "9094-9095:9090-9091"
      - "8549-8550:8545-8546"
    environment:
      - ID=2
    volumes:
      - type: bind
        source: ./temp/seed2
        target: /root
    networks:
      localnet:
        ipv4_address: 192.168.10.12

  node3:
    container_name: polard-node3
    image: "polard/seed:v0.0.0"
    ports:
      - "26665-26667:26656-26658"
      - "9096-9097:9090-9091"
      - "8551-8552:8545-8546"
    environment:
      - ID=3
    volumes:
      - type: bind
        source: ./temp/seed3
        target: /root
    networks:
      localnet:
        ipv4_address: 192.168.10.13

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
