[profile.default]
fuzz_runs = 1024
ignored_error_codes = [1878, 5574]
evm_version = 'london'
solc_version = '0.8.19'
cache = true
force = false
optimizer = false
remappings = [
    '@solmate/=lib/solmate/src/',
    '@forge-std/=lib/forge-std/src/',
    '@interfaces/=interfaces/',
    '@src/=src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
]

[profile.ci]
fuzz_runs = 8192
