# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

###############################################################################
###                           Base Configuration                            ###
###############################################################################

# The minimum gas prices a validator is willing to accept for processing a
# transaction. A transaction's fees must meet the minimum of any denomination
# specified in this config (e.g. 0.25token1;0.0001token2).
minimum-gas-prices = "0stake"

# The maximum gas a query coming over rest/grpc may consume.
# If this is set to zero, the query can consume an unbounded amount of gas.
query-gas-limit = "0"

# default: the last 362880 states are kept, pruning at 10 block intervals
# nothing: all historic states will be saved, nothing will be deleted (i.e. archiving node)
# everything: 2 latest states will be kept; pruning at 10 block intervals.
# custom: allow pruning options to be manually specified through 'pruning-keep-recent', and 'pruning-interval'
pruning = "default"

# These are applied if and only if the pruning strategy is custom.
pruning-keep-recent = "0"
pruning-interval = "0"

# HaltHeight contains a non-zero block height at which a node will gracefully
# halt and shutdown that can be used to assist upgrades and testing.
#
# Note: Commitment of state will be attempted on the corresponding block.
halt-height = 0

# HaltTime contains a non-zero minimum block time (in Unix seconds) at which
# a node will gracefully halt and shutdown that can be used to assist upgrades
# and testing.
#
# Note: Commitment of state will be attempted on the corresponding block.
halt-time = 0

# MinRetainBlocks defines the minimum block height offset from the current
# block being committed, such that all blocks past this offset are pruned
# from CometBFT. It is used as part of the process of determining the
# ResponseCommit.RetainHeight value during ABCI Commit. A value of 0 indicates
# that no blocks should be pruned.
#
# This configuration value is only responsible for pruning CometBFT blocks.
# It has no bearing on application state pruning which is determined by the
# "pruning-*" configurations.
#
# Note: CometBFT block pruning is dependant on this parameter in conjunction
# with the unbonding (safety threshold) period, state pruning and state sync
# snapshot parameters to determine the correct minimum value of
# ResponseCommit.RetainHeight.
min-retain-blocks = 0

# InterBlockCache enables inter-block caching.
inter-block-cache = true

# IndexEvents defines the set of events in the form {eventType}.{attributeKey},
# which informs CometBFT what to index. If empty, all events will be indexed.
#
# Example:
# ["message.sender", "message.recipient"]
index-events = []

# IavlCacheSize set the size of the iavl tree cache (in number of nodes).
iavl-cache-size = 10000

# IAVLDisableFastNode enables or disables the fast node feature of IAVL. 
# Default is false.
iavl-disable-fastnode = false

# AppDBBackend defines the database backend type to use for the application and snapshots DBs.
# An empty string indicates that a fallback will be used.
# The fallback is the db_backend value set in CometBFT's config.toml.
app-db-backend = ""

###############################################################################
###                         Telemetry Configuration                         ###
###############################################################################

[telemetry]

# Prefixed with keys to separate services.
service-name = ""

# Enabled enables the application telemetry functionality. When enabled,
# an in-memory sink is also enabled by default. Operators may also enabled
# other sinks such as Prometheus.
enabled = false

# Enable prefixing gauge values with hostname.
enable-hostname = false

# Enable adding hostname to labels.
enable-hostname-label = false

# Enable adding service to labels.
enable-service-label = false

# PrometheusRetentionTime, when positive, enables a Prometheus metrics sink.
prometheus-retention-time = 0

# GlobalLabels defines a global set of name/value label tuples applied to all
# metrics emitted using the wrapper functions defined in telemetry package.
#
# Example:
# [["chain_id", "cosmoshub-1"]]
global-labels = []

###############################################################################
###                           API Configuration                             ###
###############################################################################

[api]

# Enable defines if the API server should be enabled.
enable = false

# Swagger defines if swagger documentation should automatically be registered.
swagger = false

# Address defines the API server to listen on.
address = "tcp://localhost:1317"

# MaxOpenConnections defines the number of maximum open connections.
max-open-connections = 1000

# RPCReadTimeout defines the CometBFT RPC read timeout (in seconds).
rpc-read-timeout = 10

# RPCWriteTimeout defines the CometBFT RPC write timeout (in seconds).
rpc-write-timeout = 0

# RPCMaxBodyBytes defines the CometBFT maximum request body (in bytes).
rpc-max-body-bytes = 1000000

# EnableUnsafeCORS defines if CORS should be enabled (unsafe - use it at your own risk).
enabled-unsafe-cors = false

###############################################################################
###                           gRPC Configuration                            ###
###############################################################################

[grpc]

# Enable defines if the gRPC server should be enabled.
enable = true

# Address defines the gRPC server address to bind to.
address = "localhost:9090"

# MaxRecvMsgSize defines the max message size in bytes the server can receive.
# The default value is 10MB.
max-recv-msg-size = "10485760"

# MaxSendMsgSize defines the max message size in bytes the server can send.
# The default value is math.MaxInt32.
max-send-msg-size = "2147483647"

###############################################################################
###                        gRPC Web Configuration                           ###
###############################################################################

[grpc-web]

# GRPCWebEnable defines if the gRPC-web should be enabled.
# NOTE: gRPC must also be enabled, otherwise, this configuration is a no-op.
# NOTE: gRPC-Web uses the same address as the API server.
enable = true

###############################################################################
###                        State Sync Configuration                         ###
###############################################################################

# State sync snapshots allow other nodes to rapidly join the network without replaying historical
# blocks, instead downloading and applying a snapshot of the application state at a given height.
[state-sync]

# snapshot-interval specifies the block interval at which local state sync snapshots are
# taken (0 to disable).
snapshot-interval = 0

# snapshot-keep-recent specifies the number of recent snapshots to keep and serve (0 to keep all).
snapshot-keep-recent = 2

###############################################################################
###                              State Streaming                            ###
###############################################################################

# Streaming allows nodes to stream state to external systems.
[streaming]

# streaming.abci specifies the configuration for the ABCI Listener streaming service.
[streaming.abci]

# List of kv store keys to stream out via gRPC.
# The store key names MUST match the module's StoreKey name.
#
# Example:
# ["acc", "bank", "gov", "staking", "mint"[,...]]
# ["*"] to expose all keys.
keys = []

# The plugin name used for streaming via gRPC.
# Streaming is only enabled if this is set.
# Supported plugins: abci
plugin = ""

# stop-node-on-err specifies whether to stop the node on message delivery error.
stop-node-on-err = true

###############################################################################
###                         Mempool                                         ###
###############################################################################

[mempool]
# Setting max-txs to 0 will allow for a unbounded amount of transactions in the mempool.
# Setting max_txs to negative 1 (-1) will disable transactions from being inserted into the mempool.
# Setting max_txs to a positive number (> 0) will limit the number of transactions in the mempool, by the specified amount.
#
# Note, this configuration only applies to SDK built-in app-side mempool
# implementations.
max-txs = 5000

###############################################################################
###                                 Polaris                                 ###
###############################################################################
# General Polaris settings
[polaris]

[polaris.polar]
# Gas cap for RPC requests
rpc-gas-cap = "50000000"

# Timeout setting for EVM operations via RPC
rpc-evm-timeout = "5s"

# Transaction fee cap for RPC requests
rpc-tx-fee-cap = "1"


# Chain config
[polaris.polar.chain]
chain-id = "2061"

# Homestead switch block
homestead-block = "0"

# DAO fork switch block
dao-fork-block = "0"

# Whether to support DAO fork
dao-fork-support = true

# EIP150 switch block
eip150-block = "0"

# EIP155 switch block
eip155-block = "0"

# EIP158 switch block
eip158-block = "0"

# Byzanitum switch block
byzantium-block = "0"

# Constantinople switch block
constantinople-block = "0"

# Petersburg switch block
petersburg-block = "0"

# Istanbul switch block
istanbul-block = "0"

# Muir Glacier switch block
muir-glacier-block = "0"

# Berlin switch block
berlin-block = "0"

# London switch block
london-block = "0"

# Arrow Glacier switch block
arrow-glacier-block = "0"

# Gray Glacier switch block
gray-glacier-block = "0"

# Merge Netsplit switch block
merge-netsplit-block = "0"

# Shanghai switch time (nil == no fork, 0 = already on shanghai)
shanghai-time = "0"

# Cancun switch time (nil == no fork, 0 = already on cancun)
cancun-time = "<nil>"

# Prague switch time (nil == no fork, 0 = already on prague)
prague-time = "<nil>"

# Verkle switch time (nil == no fork, 0 = already on verkle)
verkle-time = "<nil>"

# Terminal total difficulty
terminal-total-difficulty = "0"

# Whether terminal total difficulty has passed
terminal-total-difficulty-passed = "true"

# DevMode enabled
is-dev-mode = false


# Miner config
[polaris.polar.miner]
# The address to which mining rewards will be sent
etherbase = "0x0000000000000000000000000000000000000000"

# Extra data included in mined blocks
extra-data = "0x"

# Gas price for transactions included in blocks
gas-price = "1000000000"

# Minimum gas limit for transactions included in blocks
gas-floor = "0"

# Maximum gas limit for transactions included in blocks
gas-ceil = "30000000"

# Whether to enable recommit feature
recommit = "2s"

# Timeout for creating a new payload
new-payload-timeout = "2s"


# Gas price oracle settings for Polaris
[polaris.polar.gpo]
# Number of blocks to check for gas prices
blocks = "20"

# Percentile of gas price to use
percentile = "60"

# Maximum header history for gas price determination
max-header-history = "1024"

# Maximum block history for gas price determination
max-block-history = "1024"

# Default gas price value
default = "1000000000"

# Maximum gas price value
max-price = "500000000000000"

# Prices to ignore for gas price determination
ignore-price = "2"

# LegacyTxPool settings
[polaris.polar.legacy-tx-pool]

# Addresses that should be treated by default as local
locals = []

# Whether local transaction handling should be disabled
no-locals = false

# Journal of local transactions to survive node restarts
journal = "transactions.rlp"

#  Time interval to regenerate the local transaction journal
rejournal = "1h0m0s"

# Minimum gas price to enforce for acceptance into the pool
price-limit = "1"

# Minimum price bump percentage to replace an already existing transaction (nonce)
price-bump = "10"

# Number of executable transaction slots guaranteed per account
account-slots = "16"

#  Maximum number of executable transaction slots for all accounts
account-queue = "64"

# Maximum number of non-executable transaction slots permitted per account
global-slots = "5120"

# Maximum number of non-executable transaction slots for all accounts
global-queue = "1024"

# Maximum amount of time non-executable transaction are queued
lifetime = "3h0m0s"


# Node-specific settings
[polaris.node]
# Name of the node
name = "polaris-geth"

# User identity associated with the node
user-ident = ""

# Version of the node
version = ""

# Directory for storing node data
data-dir = ""

# Directory for storing node keys
key-store-dir = ""

# Path to the external signer
external-signer = ""

# Whether to use lightweight KDF
use-lightweight-kdf = false

# Allow insecure unlock
insecure-unlock-allowed = false

# USB setting for the node
usb = false

# Path to smart card daemon
smart-card-daemon-path = ""

# IPC path for the node
ipc-path = ""

# Host for HTTP requests
http-host = "0.0.0.0"

# Port for HTTP requests
http-port = 8545

# CORS settings for HTTP
http-cors = ["*"]

# Virtual hosts for HTTP
http-virtual-hosts = ["*"]

# Enabled modules for HTTP
http-modules = ["net", "web3", "eth", "web3", "net", "txpool", "debug"]

# Path prefix for HTTP
http-path-prefix = ""

# Address for authentication
auth-addr = "localhost"

# Port for authentication
auth-port = 8551

# Virtual hosts for authentication
auth-virtual-hosts = ["localhost"]

# Host for WebSockets
ws-host = "0.0.0.0"

# Port for WebSockets
ws-port = 8546

# Path prefix for WebSockets
ws-path-prefix = ""

# Origins allowed for WebSockets
ws-origins = ["*"]

# Enabled modules for WebSockets
ws-modules = ["net", "web3", "eth"]

# Expose all settings for WebSockets
ws-expose-all = false

# CORS settings for GraphQL
graphql-cors = []

# Virtual hosts for GraphQL
graphql-virtual-hosts = ["localhost"]

# Allow unprotected transactions
allow-unprotected-txs = false

# Limit for batch requests
batch-request-limit = 1000

# Maximum size for batch responses
batch-response-max-size = 25000000

# JWT secret for authentication
jwt-secret = ""

# Database engine for the node
db-engine = ""


# HTTP timeout settings for the node
[polaris.node.http-timeouts]
# Timeout for reading HTTP requests
read-timeout = "30s"

# Timeout for reading HTTP request headers
read-header-timeout = "30s"

# Timeout for writing HTTP responses
write-timeout = "30s"

# Timeout for idle HTTP connections
idle-timeout = "2m0s"
