# SPDX-License-Identifier: BUSL-1.1
#
# Copyright (C) 2023, Berachain Foundation. All rights reserved.
# Use of this software is govered by the Business Source License included
# in the LICENSE file of this repository and at www.mariadb.com/bsl11.
#
# ANY USE OF THE LICENSED WORK IN VIOLATION OF THIS LICENSE WILL AUTOMATICALLY
# TERMINATE YOUR RIGHTS UNDER THIS LICENSE FOR THE CURRENT AND ALL OTHER
# VERSIONS OF THE LICENSED WORK.
#
# THIS LICENSE DOES NOT GRANT YOU ANY RIGHT IN ANY TRADEMARK OR LOGO OF
# LICENSOR OR ITS AFFILIATES (PROVIDED THAT YOU MAY USE A TRADEMARK OR LOGO OF
# LICENSOR AS EXPRESSLY REQUIRED BY THIS LICENSE).
#
# TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE LICENSED WORK IS PROVIDED ON
# AN “AS IS” BASIS. LICENSOR HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS,
# EXPRESS OR IMPLIED, INCLUDING (WITHOUT LIMITATION) WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND
# TITLE.

name: e2e

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-base:
    strategy:
      matrix:
        docker-type: [base] # Changed docker-version to docker-type for consistency with the Makefile
        os: [polaris-linux-latest]
        go-version: [1.21.1]
        arch: [amd64] # Changed go-arch to arch for consistency with the Makefile
        image-name: ["polard/base"]
        export-name: [base-image]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image using Makefile
        run: make docker-build DOCKER_TYPE=${{ matrix.docker-type }} ARCH=${{ matrix.arch }} GO_VERSION=${{ matrix.go-version }}
        env:
          GOPATH: /home/runner/go

      - name: Save base image
        run: docker save ${{ matrix.image-name }}:$GITHUB_SHA -o ${{ matrix.export-name }}.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.export-name }}
          path: ${{ matrix.export-name }}.tar

  build-localnet:
    needs: build-base
    strategy:
      matrix:
        namespace: [cosmos]
        docker-type: [localnet] # Changed docker-version to docker-type for consistency with the Makefile
        os: [polaris-linux-latest]
        go-version: [1.21.1]
        arch: [amd64] # Changed go-arch to arch for consistency with the Makefile
        base-image: [base-image]
        image-name: ["polard/localnet"]
        export-name: [localnet]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download image artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.base-image }}

      - name: Load image
        run: docker load -i ${{ matrix.base-image }}.tar

      - name: Build Docker Image using Makefile
        run: make docker-build DOCKER_TYPE=${{ matrix.docker-type }} ARCH=${{ matrix.arch }} GO_VERSION=${{ matrix.go-version }}
        env:
          GOPATH: /home/runner/go

      - name: Save base image
        run: docker save ${{ matrix.image-name }}:$GITHUB_SHA -o ${{ matrix.export-name }}.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.export-name }}
          path: ${{ matrix.export-name }}.tar

  hive:
    needs: build-base
    strategy:
      matrix:
        os: [polaris-linux-latest]
        go-version: [1.21.1]
        base-image: [base-image]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download image artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.base-image }}
      - name: Load image
        run: docker load -i ${{ matrix.base-image }}.tar
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run `make test-hive`
        run: make hive-setup test-hive
        env:
          GOPATH: /home/runner/go

  ci:
    needs: build-localnet
    strategy:
      matrix:
        namespace: ["e2e", "localnet"]
        os: [polaris-linux-latest]
        go-version: [1.21.1]
        base-image: [localnet]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Download image artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.base-image }}
      - name: Load image
        run: docker load -i ${{ matrix.base-image }}.tar
      - name: Cache Golang Deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: Run ${{ matrix.namespace }}
        run: make test-${{ matrix.namespace }}
        env:
          GOPATH: /home/runner/go
